### PR TITLE
Remove reliance on camel case

### PR DESCRIPTION
**Pull request by rmorshea**
Builds on top of https://github.com/idom-team/flake8-idom-hooks/pull/9 with minor improvements

### CODE REVIEW

**Comment by Archmonger** [comment]
Using regex to get that idom.component.component case seems a bit overkill imo. I'm okay with it though.

You might want to add a test for it if you're complicating things just for that accomodation.

👎 to force pushing a remote branch though 🥺

**Comment by rmorshea** [comment]
did i do that again? this is a new PR

**Comment by Archmonger** [comment]
Yep 
image

**Comment by Archmonger** [comment]
Ohhh I see it is a new PR. Didn't pay close enough attention while reading on mobile.

**Review by Archmonger — APPROVED** [review]

**Pull request merged**
